# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Fractal Rabbit
email: adam.strickland@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Follow me down the rabbit hole!  The water's warm, if a bit murky...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fractalrabbit.com" # the base hostname & protocol for your site
twitter_username: adamstrickland
github_username:  adamstrickland

# Build settings
markdown: kramdown

gems: [jekyll-mermaid]

cdn_root: https://www.dropbox.com/s/bsz3icp8yvmbcdd

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

